server:
  port: 6666

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: etrackhis
    password: etrackhis

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 6000
      login-timeout: 6000
      minimum-idle: 3
      auto-commit: false
      maximum-pool-size: 10
      max-lifetime: 1800000
    dynamic:
      primary: master
      strict: false
      p6spy: false
      lazy: true
      datasource:
        master:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
          username: etrackhis
          password: etrackhis

  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: com.etrackhis.autoproject.domain
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    id-type: ASSIGN_ID
    capital-mode: false

etrack:
  auto:
    poolSize: 5
    threadName: TaskThread
    inter-id-list:
      - "TEST001"

logging:
  level:
    com.etrackhis: INFO
  file:
    name: logs/auto-project.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"